### ISSUE TITLE
Error while building on android.

### ISSUE THREAD

**Issue by sandy912** [sarriaroman/photoviewer#154]
Error log:
BUILD FAILED in 3s
27 actionable tasks: 7 executed, 20 up-to-date
/Users/sandy/work/deviceapi/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/sandy/Work/deviceapi/platforms/android/app/src/main/java/com/sarriaroman/PhotoViewer/PhotoActivity.java:169: error: cannot find symbol
    private Piccasso setOptions(Piccasso picasso) throws JSONException {
                                ^
  symbol:   class Piccasso
  location: class PhotoActivity
/Users/sandy/Work/deviceapi/platforms/android/app/src/main/java/com/sarriaroman/PhotoViewer/PhotoActivity.java:169: error: cannot find symbol
    private Piccasso setOptions(Piccasso picasso) throws JSONException {
            ^
  symbol:   class Piccasso
  location: class PhotoActivity
/Users/sandy/Work/deviceapi/platforms/android/app/src/main/java/com/sarriaroman/PhotoViewer/PhotoActivity.java:224: error: cannot find symbol
                    Piccasso picasso = Picasso.with(PhotoActivity.this)

**Comment by harshzalavadiya** [comment]
Same happned to me use 1.1.18 as workaround
`ionic cordova plugin add com-sarriaroman-photoviewer@1.1.18`

**Comment by sandy912** [comment]
> Same happned to me use 1.1.18 as workaround
> `ionic cordova plugin add com-sarriaroman-photoviewer@1.1.18`

Thank you. Working like charm.
Is there any workaround for slide down, slide up to close image?

**Comment by sarriaroman** [comment]
You can now use the version 1.1.21. Must fix the issue.

**Comment by wilguevara** [comment]
Using version 1.1.18 Works for me with this dev env:
@sandy912 thanks.
```
Ionic:

   ionic (Ionic CLI)  : 4.8.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 5 other plugins)

System:

   Android SDK Tools : 25.2.5 (/usr/local/opt/android-sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 7.0.0
   NodeJS            : v6.9.5 (/usr/local/bin/node)
   npm               : 6.5.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000 
```

**Comment by WillPoulson** [comment]
Using version 1.1.18 didn't resolve the issue for me. Any other suggested fixes?

**Comment by sam-higton** [comment]
@WillPoulson Have you tried removing and reinstalling the plugin? Also, regenerating the platform directory could fix it too.

**Comment by WillPoulson** [comment]
@sam-higton Hi Sam, Yea I've tried both. It's building on a new virtual environment every build. Just trying version 1.2.0 now to see if it fixes anything?

**Comment by WillPoulson** [comment]
Version 1.2.0 still resulting in PhotoActivity.java:171: error: cannot find symbol.

Any help would be very appreciated. Thanks.

**Comment by EricKit** [comment]
@sam-higton Same here with line 171 179 and 224. 224 looks like it has two C's in Picasso which when I change creates other issues.

**Comment by slagumen** [comment]
Hi, Any news on this issue ? i had encounter the same problem. Thanks

**Comment by gaurav-chandra** [comment]
+1 on 1.2.0

**Comment by WillPoulson** [comment]
@gaurav-chandra +1 for working or not working?

**Comment by gaurav-chandra** [comment]
sorry, +1 for not working on 1.2.0 version

**Comment by slagumen** [comment]
Same here, 1.2.0 not building on android.

**Comment by moplin** [comment]
Hi my friends, I am having (i guess) the same problem.
Already tried with "1.1.18" and "^1.2.0" with no luck.

I am using:
"cordova-android": "7.1.4",
"cordova-ios": "4.5.5",

No problem on ios build.
- did tired removing and re adding the as platform android.
```
BUILD FAILED in 3s
cmd: Command failed with exit code 1 Error output:
D:\Projects\FurionProjects\mm-ionic\platforms\android\app\src\main\java\com\sarriaroman\PhotoViewer\PhotoActivity.java:171: e
rror: cannot find symbol
            picasso.fit();
                   ^
  symbol:   method fit()
  location: variable picasso of type Picasso
D:\Projects\FurionProjects\mm-ionic\platforms\android\app\src\main\java\com\sarriaroman\PhotoViewer\PhotoActivity.java:175: e
rror: cannot find symbol
            picasso.centerInside();
                   ^
  symbol:   method centerInside()
  location: variable picasso of type Picasso
D:\Projects\FurionProjects\mm-ionic\platforms\android\app\src\main\java\com\sarriaroman\PhotoViewer\PhotoActivity.java:179: e
rror: cannot find symbol
            picasso.centerCrop();
                   ^
  symbol:   method centerCrop()
  location: variable picasso of type Picasso
D:\Projects\FurionProjects\mm-ionic\platforms\android\app\src\main\java\com\sarriaroman\PhotoViewer\PhotoActivity.java:200: e
rror: cannot find symbol
                    .into(photo, new com.squareup.picasso.Callback() {
                    ^
  symbol:   method into(ImageView,<anonymous Callback>)
  location: class Picasso
D:\Projects\FurionProjects\mm-ionic\platforms\android\app\src\main\java\com\sarriaroman\PhotoViewer\PhotoActivity.java:224: e
rror: cannot find symbol
                    Piccasso picasso = Picasso.with(PhotoActivity.this)
                    ^
  symbol: class Piccasso

```

**Comment by harshzalavadiya** [comment]
basically error states that it's not able to resolve library

try opening created platform in android studio and check if there's any play services mismatch with other plugins if any or maven mirror missing.

if not working then please create gist of log and then we can see

**Comment by moplin** [comment]
@harshzalavadiya Did what you said.
Full uninstall and re build, it worked.
Added 
```
$ ionic cordova plugin add com-sarriaroman-photoviewer
$ npm install --save @ionic-native/photo-viewer
```
Build again, failed with the same error

**Comment by harshzalavadiya** [comment]
@moplin can you provide error log as a gist. and if you are using ionic4 then use `@ionic-native/photo-viewer@beta` if v3 then it's fine.

instead of
`ionic cordova plugin add com-sarriaroman-photoviewer`
try
`ionic cordova plugin add com-sarriaroman-photoviewer@1.1.18`

**Comment by harshzalavadiya** [comment]
@moplin glad it worked :tada: ,

Basically there was no need of removing `node_modules` or `plugins` folder as when you uninstall plugin cordova takes care of cleaning it up completely but sometimes there are chance of conflict that will break build so removing plugin by cli and deleting platform should have done the trick :wink:

**Comment by WillPoulson** [comment]
Thank you, turns out it wasn't changing/removing the version in the package.json. Problem solved.

**Comment by FabianTe** [comment]
This works for **Ionic 4**:

`com-sarriaroman-photoviewer@1.1.18`
`@ionic-native/photo-viewer@beta`

```
Ionic:

   ionic (Ionic CLI)             : 4.9.0
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.12.3
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.2, (and 10 other plugins)

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

**Comment by tobiasmuecksch** [comment]
I tried version 1.1.18 and 1.20. Both have the same issue for me.

**Comment by niuwenbo** [comment]
@moplin same solutions but also has this issue.has anyone solutions

**Comment by RELAXccc** [comment]
> @moplin same solutions but also has this issue.has anyone solutions

```
ionic cordova plugin remove com-sarriaroman-photoviewer
ionic cordova platform remove android
ionic cordova plugin add com-sarriaroman-photoviewer@1.1.18
```
worked for me. 

I should have the newest ionic 4 libs (did npm update today)

**Comment by Qobiljon** [comment]
> Same happned to me use 1.1.18 as workaround
> `ionic cordova plugin add com-sarriaroman-photoviewer@1.1.18`

You're the best !

**Comment by thameurr** [comment]
After install it i get the same error : 
`Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91`
