### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by northkode** [sarriaroman/photoviewer#43]
sarriaroman/PhotoViewer/PhotoViewer.java:37: error: cannot find symbol
            if (cordova.hasPermission(READ) && cordova.hasPermission(WRITE)) {
                       ^
looks like its missing the permission helper to work with older cordova 5 versions.

**Comment by marciogurka** [comment]
hey @northkode, I had the same problem using this plugin, but I updated my cordova using the CLI command `cordova platform update android@5.0.0` and it worked fine!

**Comment by northkode** [comment]
Ya I noticed they don't support earlier so I wrote a fix for it to user cordova permission helper. 

Cheers

Kyle Jeske

On Tue, Nov 22, 2016 at 12:48 PM "Márcio José Gurka Júnior"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

hey
https://github.com/northkode
, I had the same problem using this plugin, but I updated my cordova using the CLI command

cordova platform update android@5.0.0

and it worked fine!

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/sarriaroman/photoviewer/issues/43#issuecomment-262345968
, or

**Comment by sarriaroman** [comment]
Won't work on older Cordova versions than 5.0
